module.exports = {
  SONGS_RECEIVED: "SONGS_RECEIVED",
  SONG_RECEIVED: "SONG_RECEIVED",
  CLEAR_SONG: "CLEAR_SONG",
  REMOVE_SONG: "REMOVE_SONG",
  SONG_UPDATE_RECEIVED: "SONG_UPDATE_RECEIVED",
  CLEAR_ALL_SONGS: "CLEAR_ALL_SONGS"
};
